### ISSUE TITLE
Расписать модель Спотифай более подробно

### ISSUE THREAD

**Issue by solarrust** [solarrust/hacker-laws#18]
@Realetive привет!

Ты говорил, что есть желание более подробно расписать эту концепцию =)
You are welcome! 🖤

**Comment by Realetive** [comment]
![2YBNXwwEhzw](https://user-images.githubusercontent.com/2073959/60389329-3c75ca80-9ac8-11e9-94b3-b93b8dc14ab0.jpg)

#25

**Comment by solarrust** [comment]
![giphy](https://user-images.githubusercontent.com/13676514/60389365-c45bd480-9ac8-11e9-9adb-4169f8ce901d.gif)
